# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: environment
    type: string
    default: 'dev'
    values:
      - dev
      - staging
      - prod

variables:
  - ${{ if eq(parameters.environment, 'dev') }}:
      group: dev-variables
  - ${{ if eq(parameters.environment, 'staging') }}:
      group: staging-variables
  - ${{ if eq(parameters.environment, 'prod') }}:
      group: prod-variables
    
  PYTHONPATH: '.'

stages:
- stage: BuildAndTest
  displayName: 'Build and Test the API'
  jobs:
  - job: Build
    displayName: 'Build and Lint'
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - checkout: self

    - script: |
        mkdir -p ./secrets

        curl -s -X POST https://login.microsoftonline.com/$(TENANT_ID)/oauth2/v2.0/token \
          -d "client_id=$(DEVOPS_AZURE_CLIENT_ID)" \
          -d "client_secret=$(DEVOPS_CLIENT_SECRET)" \
          -d "scope=$(AZURE_API_SCOPE)" \
          -d "grant_type=client_credentials" \
          | jq -r '.access_token' > ./secrets/token.txt

        if grep -q null ./secrets/token.txt; then
          echo "Failed to obtain token"
          exit 1
        fi
      displayName: 'Get Azure AD Access Token'

    - script: |
        LENGTH=$(cat ./secrets/token.txt | wc -c)
        echo "Access token length: $LENGTH characters"
      displayName: 'Show token length'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.13'
        addToPath: true

    - script: pip install -r requirements.txt
      displayName: 'Install requirements'

    - script: mkdir -p reports
      displayName: 'Create shared reports directory'

    - script: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 10
      displayName: 'Start FastAPI App'
      env:
        TENANT_ID: $(TENANT_ID)
        API_APP_ID: $(API_APP_ID)
        CLIENT_APP_ID: $(CLIENT_APP_ID)
        CLIENT_SECRET: $(CLIENT_SECRET)

    - script: curl -I http://localhost:8000/openapi.json
      displayName: 'Check FastAPI /openapi.json response'

    # Optional: Replace this with Docker-based ZAP if needed
    - script: |
        echo "You must replace this with a Docker-based OWASP ZAP scan or a task script"
      displayName: 'ZAP Scan Placeholder'

    - script: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      displayName: 'Lint with flake8'

    - script: bandit -r . --exclude ./tests,.vscode,.github
      displayName: 'Run Bandit scan'

    - script: |
        pip install safety
        safety check --full-report --key=$(SAFETY_API_KEY)
      displayName: 'Run Safety CLI'

    - script: pytest
      displayName: 'Run Unit Tests'
      env:
        TENANT_ID: $(TENANT_ID)
        API_APP_ID: $(API_APP_ID)
        CLIENT_APP_ID: $(CLIENT_APP_ID)
        CLIENT_SECRET: $(CLIENT_SECRET)

