name: Build And Test The API
env:
  PYTHONPATH: .
on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test

    services:
      redis:  # Remove if not needed, add other services if required
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest bandit safety httpx uvicorn
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Static security scan with Bandit
      run: bandit -r . --exclude ./tests,.vscode,.github

    - name: Run Safety CLI to check for vulnerabilities
      uses: pyupio/safety-action@v1
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}
        args: --detailed-output # To always see detailed output from this action

    - name: Run unit tests
      run: pytest
      env:
        TENANT_ID: ${{ vars.TENANT_ID }}
        API_APP_ID: ${{ vars.API_APP_ID }}
        CLIENT_APP_ID: ${{ vars.CLIENT_APP_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

    - name: Start FastAPI app in background
      run: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 10
      env:
        TENANT_ID: ${{ vars.TENANT_ID }}
        API_APP_ID: ${{ vars.API_APP_ID }}
        CLIENT_APP_ID: ${{ vars.CLIENT_APP_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

    - name: Run OWASP ZAP scan
      run: |
        docker run --rm --network host -v $(pwd):/zap/wrk/:rw -t zaproxy/zap-stable zap-api-scan.py \
        -t http://localhost:8000 \
        -w zap_warnings.md \
        -f openapi \
        -u http://localhost:8000/openapi.json \
        -I

    - name: Show ZAP results
      run: cat zap_warnings.md

